elasticjob:
  tracing:
    type: RDB
  regCenter:
    # 连接Zookeeper服务器的列表,包括IP地址和端口号,多个地址用逗号分隔
    serverLists: 127.0.0.1:2181
    # Zookeeper的命名空间
    namespace: cy
    # 等待重试的间隔时间的初始值   单位：毫秒
    base-sleep-time-milliseconds: 10000
    # 等待重试的间隔时间的最大值
    max-sleep-time-milliseconds: 30000
    # 最大重试次数
    max-retries: 3
    # 会话超时时间 单位: 毫秒
    session-timeout-milliseconds: 600000
    # 连接超时时间 单位: 毫秒
    connection-timeout-milliseconds: 600000
    # elasticjob.jobs 是一个 Map，
    # key 为作业名称，value 为作业类型与配置。
    # Starter 会根据该配置自动创建 OneOffJobBootstrap 或 ScheduleJobBootstrap 的实例
    # 并注册到 Spring 容器中。
  jobs:
    TestJobMany:
      # elasticJobClass 与 elasticJobType 互斥，每项作业只能有一种类型
      elasticJobClass: com.yanhuohui.elasticjobdemo.demos.myjobs.MyElasticJob
      # 作业分片总数
      shardingTotalCount: 2
      jobListenerTypes: myElasticJobListener
      # 错误处理策略:记录日志策略、记录作业异常日志，但不中断作业执行
      # LOG : 记录日志策略、记录作业异常日志，但不中断作业执行
      # THROW : 抛出异常策略	抛出系统异常并中断作业执行
      # IGNORE : 忽略异常策略	忽略系统异常且不中断作业执行
      # WECHAT : 企业微信通知策略	发送企业微信消息通知，但不中断作业执行
      jobErrorHandlerType: LOG
      cron: 0 */5 * * * ?
      shardingItemParameters: 0=A,1=B
      # 作业线程池处理策略
      jobExecutorServiceHandlerType: "SINGLE_THREAD"
      # 本地配置是否可覆盖注册中心配置 , 如果可覆盖，每次启动作业都以本地配置为准
      overwrite: true
      # 是否开启错过任务重新执行
      misfire: true
      #是否开启任务执行失效转移，开启表示如果作业在一次任务执行中途宕机，允许将该次未完成的任务在另一作业节点上补偿执行
      failover: true