server:
  port: 8080

spring:
  profiles:
    include: job
  application:
    name: elasticjobdemoproject
  datasource:
    url: jdbc:mysql://localhost:3306/elasticjob?useUnicode=true&useSSL=false&allowLoadLocalInfile=false&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456








